# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html

# For images not loading, see this page :
# https://github.com/liip/LiipImagineBundle/issues/850
# Try to empty the browser cache
# brave://settings/clearBrowserData

liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    resolvers :
        default :
            web_path : ~


    filter_sets:
        
        galerie_mini:
            quality: 75
            filters:
                auto_rotate: ~
                relative_resize:
                    widen: 200
        
        manuscrits_mini:
            quality: 75
            filters:
                auto_rotate: ~
                thumbnail:
                    size: [134, 100]
                    mode: outbound

        realisation_mini:
            quality: 75
            filters:
                auto_rotate: ~
                thumbnail:
                    size: [278, 370]
                    mode: outbound

        boutique_mini:
            quality: 75
            filters:
                auto_rotate: ~
                relative_resize:
                    widen: 150

        boutique_full:
            quality: 100
            filters:
                auto_rotate: ~
                scale:
                    dim: [600, 600]

        full:
            quality: 100
            filters:
                auto_rotate: ~
                scale:
                    dim: [1200, 1200]
