vich_uploader:
    db_driver: orm

    mappings:
       artworks_images:
           uri_prefix: '%app.path.artworks_images%'
           upload_destination: '%kernel.project_dir%/public%app.path.artworks_images%'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_update: true
           delete_on_remove: true

       products_images:
           uri_prefix: '%app.path.products_images%'
           upload_destination: '%kernel.project_dir%/public%app.path.products_images%'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_update: true
           delete_on_remove: true