---
kind: pipeline
type: ssh
name: Deploy

server:
  host:
    from_secret: HOST_ADDR
  user:
    from_secret: USER
  password:
    from_secret: PASSWORD

steps:
- name: Deploy via docker
  environment:
    APP_SECRET:
      from_secret: APP_SECRET
    DB_NAME:
      from_secret: DB_NAME
    DB_PASS:
      from_secret: DB_PASS
    DB_ROOT_PASS:
      from_secret: DB_ROOT_PASS
    DB_USER:
      from_secret: DB_USER
    STRIPE_CONFIRM_END_POINT_KEY:
      from_secret: STRIPE_CONFIRM_END_POINT_KEY
    STRIPE_PUBLIC_KEY:
      from_secret: STRIPE_PUBLIC_KEY
    STRIPE_SECRET_KEY:
      from_secret: STRIPE_SECRET_KEY
  commands:
    #- sudo cp /home/alex/vars/atelier-amelie/.env .env

    # APP VARS
    - echo APP_ENV=dev >> .env.local
    - echo APP_SECRET=$APP_SECRET >> .env.local
    - echo STRIPE_CONFIRM_END_POINT_KEY=$STRIPE_CONFIRM_END_POINT_KEY >> .env.local
    - echo STRIPE_PUBLIC_KEY=$STRIPE_PUBLIC_KEY >> .env.local
    - echo STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY >> .env.local
    - echo DATABASE_URL="mysql://$DB_USER:$DB_PASS@atelier-amelie-db:3306/$DB_NAME?serverVersion=mariadb-10.6.3" >> .env.local

    # DOCKER VARS
    - echo DB_NAME=$DB_NAME >> .env.docker
    - echo DB_PASS=$DB_PASS >> .env.docker
    - echo DB_USER=$DB_USER >> .env.docker
    - echo DB_ROOT_PASS=$DB_ROOT_PASS >> .env.docker

    # Create App    
    - sudo docker-compose -f docker-compose-prod.yml --env-file .env.docker up -d --build --force-recreate

    # Clean Docker containers & images
    - sudo docker system prune -a -f