---
kind: pipeline
type: ssh
name: Deploy

server:
  host:
    from_secret: HOST_ADDR
  user:
    from_secret: USER
  password:
    from_secret: PASSWORD

steps:
- name: Deploy via docker
  commands:
  - echo APP_ENV=PROD >> .env
  - echo APP_SECRET=$APP_SECRET >> .env
  - echo DB_USER=$DB_USER >> .env
  - echo DB_PASS=$DB_PASS >> .env
  - echo DB_ROOT_PASS=$DB_ROOT_PASS >> .env
  - echo DB_NAME=$DB_NAME >> .env
  - echo STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY >> .env
  - echo STRIPE_PUBLIC_KEY=$STRIPE_PUBLIC_KEY >> .env
  - echo STRIPE_CONFIRM_END_POINT_KEY=$STRIPE_CONFIRM_END_POINT_KEY >> .env
  - cat .env
  - printenv
  # - sudo docker-compose -f docker-compose-prod.yml build --pull --no-cache
  # - sudo docker-compose -f docker-compose-prod.yml up -d --force-recreate
  environment:
    APP_SECRET:
      from_secret: APP_SECRET
    DB_USER:
      from_secret: DB_USER
    DB_PASS:
      from_secret: DB_PASS
    DB_ROOT_PASS:
      from_secret: DB_ROOT_PASS
    DB_NAME:
      from_secret: DB_NAME
    STRIPE_SECRET_KEY:
      from_secret: STRIPE_SECRET_KEY
    STRIPE_PUBLIC_KEY:
      from_secret: STRIPE_PUBLIC_KEY
    STRIPE_CONFIRM_END_POINT_KEY:
      from_secret: STRIPE_CONFIRM_END_POINT_KEY