---
kind: pipeline
type: ssh
name: Deploy

server:
  host:
    from_secret: HOST_ADDR
  user:
    from_secret: USER
  password:
    from_secret: PASSWORD

steps:
- name: Deploy via docker
  commands:
    - echo ${APP_ENV}
    - echo ${HOST_ADDR}
    - echo ${APP_SECRET}
    - echo ${TEST}
    - echo ${UID}
  # - sudo docker-compose -f docker-compose-prod.yml build --pull --no-cache
  # - sudo docker-compose -f docker-compose-prod.yml up -d --force-recreate
  environment:
    TEST: test
    APP_ENV: prod
    APP_SECRET:
      from_secret: APP_SECRET
    DB_USER:
      from_secret: DB_USER
    DB_PASS:
      from_secret: DB_PASS
    DB_ROOT_PASS:
      from_secret: DB_ROOT_PASS
    DB_NAME:
      from_secret: DB_NAME
    STRIPE_SECRET_KEY:
      from_secret: STRIPE_SECRET_KEY
    STRIPE_PUBLIC_KEY:
      from_secret: STRIPE_PUBLIC_KEY
    STRIPE_CONFIRM_END_POINT_KEY:
      from_secret: STRIPE_CONFIRM_END_POINT_KEY