---
kind: pipeline
type: ssh
name: Deploy

server:
  host:
    from_secret: HOST_ADDR
  user:
    from_secret: USER
  password:
    from_secret: PASSWORD

steps:
- name: Deploy via docker
  environment:
    USERNAME:
      from_secret: username
  commands:
      - export USERNAME_SHOW="$USERNAME_SHOW"
      - echo $USERNAME_SHOW
    # - sudo cp /home/alex/vars/atelier-amelie/.env .env
    # - sudo docker-compose -f docker-compose-prod.yml build --pull --no-cache
    # - sudo docker-compose -f docker-compose-prod.yml up -d --force-recreate
    
---
kind: secret
name: username
data: AIJtbdfcS+HdONICoc1e2Z5EbAxV0Uy8dBf63aBA1FXP0quc