---
kind: pipeline
type: ssh
name: Deploy

server:
  host:
    from_secret: HOST_ADDR
  user:
    from_secret: USER
  password:
    from_secret: PASSWORD

steps:
- name: Deploy via docker
  environment:
    USERNAME:
      from_secret: DB_USER
  commands:
    - sudo docker-compose -f docker-compose-prod.yml build --pull --no-cache --build-arg USERNAME=$USERNAME
    # - sudo cp /home/alex/vars/atelier-amelie/.env .env
    # - sudo docker-compose -f docker-compose-prod.yml build --pull --no-cache
    # - sudo docker-compose -f docker-compose-prod.yml up -d --force-recreate