version: '3.7'
services:

    atelier-amelie-caddy:
        container_name: atelier-amelie-caddy
        build:
            context: .
            dockerfile: docker/Dockerfile-caddy
        networks:
            - atelier-amelie-frontend
        depends_on:
            - atelier-amelie-php
        ports:
            - 8888:80

    atelier-amelie-php:
        container_name: atelier-amelie-php
        build: 
            context: .
            dockerfile: docker/Dockerfile-php
        networks:
            - atelier-amelie-frontend
            - atelier-amelie-backend
        volumes:
            - atelier-amelie-public:/var/www/public
        depends_on:
            - atelier-amelie-db
        

    atelier-amelie-db:
        image: mariadb:10.6.3
        container_name: atelier-amelie-db
        networks:
            - atelier-amelie-backend
        environment:
            MYSQL_DATABASE: main
            MYSQL_ROOT_PASSWORD: password
        volumes:
            - atelier-amelie-db:/var/lib/mysql

networks:
  atelier-amelie-frontend: {}
  atelier-amelie-backend: {}

volumes:
    atelier-amelie-db:
    atelier-amelie-public:
    php_socket: